uav_names: ["uav1", "uav2", "uav3", "uav4" ,"uav5", "uav6", "uav7","uav8", "uav9", "uav10", "uav11", "uav12", "uav13", "uav14" ,"uav15"] #, "uav11"]

# odometry_topic: "estimation_manager/ground_truth/odom"
odometry_topic: "estimation_manager/odom_main"
uav_uvdar_ids: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15] # 0,1,2,3,4] #,"uav40","uav41"] #, \"uav11\"]\n

set_reference_timer:
  rate: 10 # [Hz]
  
size_neighbors1: 0.3 
size_obstacles1: 0.05 
encumbrance: 0.3 
maximum_distance_conn: 10.0
noisy_measurements: 0.0 #0.15
noisy_angle: 0.0 #0.3
threshold: 0.8 
window_length: 1 #10
bias_error: 0.0 #0.5
cwvd_obs: 0.9
cwvd_rob: 0.9
sim: true
refZ: 10.0
max_obstacle_integration_dist: 9.0

Adj_matrix_uav1: [0,0,0,0,0,0,0,0,0]
Adj_matrix_uav2: [0,0,0,0,0,0,0,0,0]
Adj_matrix_uav3: [0,0,0,0,0,0,0,0,0]
Adj_matrix_uav4: [0,0,0,0,0,0,0,0,0]
Adj_matrix_uav5: [0,0,0,0,0,0,0,0,0]
Adj_matrix_uav6: [0,0,0,0,0,0,0,0,0]
Adj_matrix_uav7: [0,0,0,0,0,0,0,0,0]
Adj_matrix_uav8: [0,0,0,0,0,0,0,0,0]
Adj_matrix_uav9: [0,0,0,0,0,0,0,0,0]
Adj_matrix_uav10: [0,0,0,0,0,0,0,0,0]
Adj_matrix_uav11: [0,0,0,0,0,0,0,0,0]
Adj_matrix_uav12: [0,0,0,0,0,0,0,0,0]
Adj_matrix_uav13: [0,0,0,0,0,0,0,0,0]
Adj_matrix_uav14: [0,0,0,0,0,0,0,0,0]
Adj_matrix_uav15: [0,0,0,0,0,0,0,0,0]

# control approach params
controlled_dimensions: 3

max_distance_to_initial_position: 2.0

#for 3D
min_z: 0.0  
max_z: 10.0

flag_3D: true
use_z_rule: false

use_livox_tilted: true
rotate_recieved_pcl: false #difference between simulation and livox
livox_tilt_deg: 45.0

d1: 0.5
d2: 1.0
d3: 0.5
d4: 1.0
d5: 0.5
d6: 1.0
d7: 0.2
radius: 3.5  #point lio 
betaD: 1.5 
beta_min: 0.1
dt: 0.15
step_size: 0.66


monitored_area_origin:
  x: 0.0
  y: 0.0
  z: 0.0

final_positions: # defined with respect to monitored_area_origin
  uav1:
    x: 0.00
    y: 0.00
    z: 1.00

  uav2:
    x: 1.90
    y: 1.74
    z: 1.71

  uav3:
    x: -0.31
    y: -3.49
    z: 2.43

  uav4:
    x: -2.50
    y: 3.26
    z: 3.14

  uav5:
    x: 4.45
    y: -0.79
    z: 3.86

  uav6:
    x: -4.04
    y: -2.57
    z: 4.57

  uav7:
    x: 1.28
    y: 4.78
    z: 5.29

  uav8:
    x: 2.30
    y: -4.44
    z: 6.00

  uav9:
    x: -4.65
    y: 1.70
    z: 6.71

  uav10:
    x: 4.43
    y: 1.83
    z: 7.43

  uav11:
    x: -1.91
    y: -4.09
    z: 8.14

  uav12:
    x: -1.23
    y: 3.92
    z: 8.86

  uav13:
    x: 3.03
    y: -1.75
    z: 9.57

  uav14:
    x: -2.52
    y: -0.55
    z: 10.29

  uav15:
    x: 0.00
    y: 0.00
    z: 11.00

initial_positions: # defined with respect to monitored_area_origin
  uav1:
    x: 0.00
    y: 0.00
    z: 11.00

  uav2:
    x: -1.90
    y: -1.74
    z: 10.29

  uav3:
    x: 0.31
    y: 3.49
    z: 9.57

  uav4:
    x: 2.50
    y: -3.26
    z: 8.86

  uav5:
    x: -4.45
    y: 0.79
    z: 8.14

  uav6:
    x: 4.04
    y: 2.57
    z: 7.43

  uav7:
    x: -1.28
    y: -4.78
    z: 6.71

  uav8:
    x: -2.30
    y: 4.44
    z: 6.00

  uav9:
    x: 4.65
    y: -1.70
    z: 5.29

  uav10:
    x: -4.43
    y: -1.83
    z: 4.57

  uav11:
    x: 1.91
    y: 4.09
    z: 3.86

  uav12:
    x: 1.23
    y: -3.92
    z: 3.14

  uav13:
    x: -3.03
    y: 1.75
    z: 2.43

  uav14:
    x: 2.52
    y: 0.55
    z: 1.71

  uav15:
    x: -0.00
    y: -0.00
    z: 1.00