uav_names: ["uav1", "uav2", "uav3", "uav4", "uav5", "uav6", "uav7", "uav8", "uav9", "uav10"] #, "uav11"]

# odometry_topic: "estimation_manager/ground_truth/odom"
odometry_topic: "estimation_manager/odom_main"

set_reference_timer:
  rate: 10 # [Hz]
  
size_neighbors1: 2.5
size_obstacles1: 0.3
maximum_distance_conn: 15.0

Adj_matrix_uav1: [0,0,0,0,0,0,0,0,0,0]
Adj_matrix_uav2: [0,0,0,0,0,0,0,0,0,0]
Adj_matrix_uav3: [0,0,0,0,0,0,0,0,0,0]
Adj_matrix_uav4: [0,0,0,0,0,0,0,0,0,0]
Adj_matrix_uav5: [0,0,0,0,0,0,0,0,0,0]
Adj_matrix_uav6: [0,0,0,0,0,0,0,0,0,0]
Adj_matrix_uav7: [0,0,0,0,0,0,0,0,0,0]
Adj_matrix_uav8: [0,0,0,0,0,0,0,0,0,0]
Adj_matrix_uav9: [0,0,0,0,0,0,0,0,0,0]
Adj_matrix_uav10: [0,0,0,0,0,0,0,0,0,0]

# control approach params
controlled_dimensions: 3

max_distance_to_initial_position: 2.0


d1: 1.0
d2: 7.5
d3: 1.0
d4: 7.5
radius: 10.0 
encumbrance: 2.5
betaD: 1.5
beta_min: 0.5
dt: 0.01
step_size: 0.075

obstacle1: [0.0,1.0] #-3.0,24.0]
obstacle2 : [-6.0,3.0] #6.5,19.0]
obstacle3 : [8.0,-7.0] #-4.5,15.0]

monitored_area_origin:
  x: -0.0
  y: 0.0
  z: 3.0


final_positions: # defined with respect to monitored_area_origin

  uav1:
    x: 15.0
    y: 0
    z: 3.0

  uav2:
    x: 12.13
    y: 8.81
    z: 3.0

  uav3:
    x: 4.63
    y: 14.26
    z: 3.0
  
  uav4:
    x: -4.63
    y: 14.26
    z: 3.0

  uav5:
    x: -12.13
    y: 8.81
    z: 3.0

  uav6:
    x: -15.0
    y: 1.83
    z: 3.0

  uav7:
    x: -12.13
    y: -8.81
    z: 3.0
    
  uav8:
    x: -4.63
    y: -14.26
    z: 3.0

  uav9:
    x: 4.63
    y: -14.26
    z: 3.0

  uav10:
    x: 12.13
    y: -8.81
    z: 3.0



initial_positions: # defined with respect to monitored_area_origin


  uav1:
    x: -15.0
    y: 0
    z: 3.0

  uav2:
    x: -12.13
    y: -8.81
    z: 3.0

  uav3:
    x: -4.63
    y: -14.26
    z: 3.0
  
  uav4:
    x: 4.63
    y: -14.26
    z: 3.0

  uav5:
    x: 12.13
    y: -8.81
    z: 3.0

  uav6:
    x: 15.0
    y: -1.83
    z: 3.0

  uav7:
    x: 12.13
    y: 8.81
    z: 3.0
    
  uav8:
    x: 4.63
    y: 14.26
    z: 3.0

  uav9:
    x: -4.63
    y: 14.26
    z: 3.0

  uav10:
    x: -12.13
    y: 8.81
    z: 3.0
