simulation_rate: 200.0
clock_rate: 100.0
realtime_factor: 0.4

iterate_without_input: true

individual_takeoff_platform:
  enabled: false

collisions:
  enabled: true
  crash: true

  # if crash==false, then the collisions are elastic
  rebounce: 100.0

# randomization of the initial conditions around the desired spawn point
randomization:

  enabled: false

  bounds:
    x: 15.0
    y: 15.0
    z: 15.0

ground:
  enabled: true
  z: 0.0 # [m]
#


uav_names: [
  "uav1",
  "uav2",
  "uav3",
  "uav4",
  "uav5",  
  "uav6",
  "uav7",
  "uav8",  
  "uav9",
  "uav10",
]

uav1:
  type: "x500"
  spawn:
    x: 10
    y: 0
    z: 2.0
    heading: 0.0

uav2:
  type: "x500"
  spawn:
    x: -12.13
    y: -8.81
    z: 2.0
    heading: 0.0

uav3:
  type: "x500"
  spawn:
    x: -4.63
    y: -14.26
    z: 2.0
    heading: 0.0

uav4:
  type: "x500"
  spawn:
    x: 4.63
    y: -14.26
    z: 2.0
    heading: 0.0

uav5:
  type: "x500"
  spawn:
    x: 12.13
    y: -8.81
    z: 2.0
    heading: 0.0

uav6:
  type: "x500"
  spawn:
    x: 15.0
    y: -1.83
    z: 2.0
    heading: 0.0

uav7:
  type: "x500"
  spawn:
    x: 12.13
    y: 8.81
    z: 2.0
    heading: 0.0
    
uav8:
  type: "x500"
  spawn:
    x: 4.63
    y: 14.26
    z: 2.0
    heading: 0.0

uav9:
  type: "x500"
  spawn:
    x: -4.63
    y: 14.26
    z: 2.0
    heading: 0.0

uav10:
  type: "x500"
  spawn:
    x: -12.13
    y: 8.81
    z: 2.0
    heading: 0.0




