safe_obstacle_distance:
  default: 1.0 # [m]

# euclidean_distance_cutoff: 0.7 # [m]

unknown_is_occupied: false # if false, planning through unknown space is enabled

subt_planner:
  use: true

trajectory_generator:
  turn_in_flight_direction: true
  heading_offset: 0.0 # [rad]