simulation_rate: 100.0
clock_rate: 100.0
realtime_factor: 0.7

iterate_without_input: true

individual_takeoff_platform:
  enabled: false

collisions:
  enabled: true
  crash: true

  # if crash==false, then the collisions are elastic
  rebounce: 100.0

# randomization of the initial conditions around the desired spawn point
randomization:

  enabled: false

  bounds:
    x: 15.0
    y: 15.0
    z: 15.0

ground:
  enabled: true
  z: 0.0 # [m]
#


uav_names: [
  "uav1",
  "uav2",
  "uav3",
  "uav4",
  "uav5",
]



uav1:
  type: "x500"
  spawn:
    x: 0.00
    y: 0.00
    z: 11.00
    heading: 0.0

uav2:
  type: "x500"
  spawn:
    x: -3.19
    y: -2.92
    z: 8.50
    heading: 0.0

uav3:
  type: "x500"
  spawn:
    x: 0.44
    y: 4.98
    z: 6.00
    heading: 0.0

uav4:
  type: "x500"
  spawn:
    x: 2.63
    y: -3.44
    z: 3.50
    heading: 0.0

uav5:
  type: "x500"
  spawn:
    x: 10.00
    y: 0.00
    z: 1.00
    heading: 0.0

