uav_names: ["uav29"] #,"uav40","uav41"] #, \"uav11\"]\n
uav_uvdar_ids: [2] #,"uav40","uav41"] #, \"uav11\"]\n
# odometry_topic: "estimation_manager/ground_truth/odom"
odometry_topic: "estimation_manager/odom_main"

set_reference_timer:
  rate: 10 # [Hz]
  
size_neighbors1: 0.3 
size_obstacles1: 0.1
encumbrance: 0.5 
maximum_distance_conn: 10.0
noisy_measurements: 0.0 #0.15
noisy_angle: 0.0 #0.3
threshold: 0.8 
window_length: 1 #10
bias_error: 0.0 #0.5
tolerance: 0.5
deafult_decay_rate: 0.05
remove_threshold: 0.2
cwvd_obs: 0.8
cwvd_rob: 0.8
cwvd: 0.95

sim: false
refZ: 1.1
max_obstacle_integration_dist: 8.0
#Adj_matrix_uav1: [0,1,1,0,0]
#Adj_matrix_uav2: [1,0,1,1,1]
#Adj_matrix_uav3: [1,1,0,1,0]
#Adj_matrix_uav4: [0,1,1,0,1]
#Adj_matrix_uav5: [0,1,0,1,0]

Adj_matrix_uav29: [0]
#Adj_matrix_uav1: [0,0,0,0,0]
#Adj_matrix_uav2: [0,0,0,0,0]
#Adj_matri5_uav3: [0,0,0,0,0]
#Adj_matrix_uav4: [0,0,0,0,0]
#Adj_matrix_uav5: [0,0,0,0,0]

# control approach params
controlled_dimensions: 3

max_distance_to_initial_position: 2.0

#for 3D
min_z: 0.5  
max_z: 20.0

flag_3D: true
use_z_rule: false

use_livox_tilted: true
rotate_recieved_pcl: false #difference between simulation and livox
livox_tilt_deg: 20.0
livox_fov: 60.0

searchRadius: 0.6 #For meshing - max search for vertice in triangle SHOULD BE SET ACCORDINGLY WITH THE PCL I AM GETTING - mapping res 0.4 vox grid -> 0.6 serach radius
use_bonxai_mapping: true #if true usis mapping to shape the cell S otherwise it uses the pointcloud for slam IF FALSE set frame for rbl as uav29/livox
# if true set frame as point_lio_origin
use_voxel: true #I started to use meshing to cut cell A instead of this, but this seems as a smarter alternative - should work for mapping wiht bonxai and also with raw point cloud
map_resolution: 0.3

d1: 0.5
d2: 1.0
d3: 0.5
d4: 1.0
d5: 0.5
d6: 1.0
d7: 0.2
radius: 3.5 
betaD: 0.5 
beta_min: 0.1
dt: 0.15
step_size: 0.15

monitored_area_origin:
  x: 0.0
  y: 0.0
  z: 0.0

final_positions: # defined with respect to monitored_area_origin

  uav29:
    x: 30.0
    y: 0.0 
    z: 1.5
  
initial_positions: # defined with respect to monitored_area_origin

  uav29:
    x: 0.0 #10
    y: 0.0 #0
    z: 1.1


