simulation_rate: 100.0
clock_rate: 100.0
realtime_factor: 0.2

iterate_without_input: true

individual_takeoff_platform:
  enabled: false

collisions:
  enabled: true
  crash: true

  # if crash==false, then the collisions are elastic
  rebounce: 100.0

# randomization of the initial conditions around the desired spawn point
randomization:

  enabled: false

  bounds:
    x: 15.0
    y: 15.0
    z: 15.0

ground:
  enabled: true
  z: 0.0 # [m]
#


uav_names: [
  "uav1",
  "uav2",
  "uav3",
  "uav4",
  "uav5",
]



uav1:
  type: "x500"
  spawn:
    x: 8.09
    y: -5.88
    z: 10.0
    heading: 0.0

uav2:
  type: "x500"
  spawn:
    x: 8.09
    y: 5.88
    z: 10.0
    heading: 0.0

uav3:
  type: "x500"
  spawn:
    x: -3.09
    y: 9.51
    z: 10.0
    heading: 0.0

uav4:
  type: "x500"
  spawn:
    x: -10.00
    y: -0.00
    z: 10.0
    heading: 0.0

uav5:
  type: "x500"
  spawn:
    x: -3.09
    y: -9.51
    z: 10.0
    heading: 0.0

