uav_names: ["uav39"] #,"uav40","uav41"] #, \"uav11\"]\n
uav_uvdar_ids: [2] #,"uav40","uav41"] #, \"uav11\"]\n
# odometry_topic: "estimation_manager/ground_truth/odom"
odometry_topic: "estimation_manager/odom_main"

set_reference_timer:
  rate: 10 # [Hz]
  
size_neighbors1: 0.2
size_obstacles1: 0.5
encumbrance: 0.2
maximum_distance_conn: 10.0
noisy_measurements: 0.0 #0.15
noisy_angle: 0.0 #0.3
threshold: 1.0 
window_length: 1 #10
bias_error: 0.0 #0.5
tolerance: 0.5
deafult_decay_rate: 0.05
remove_threshold: 0.2
#Adj_matrix_uav1: [0,1,1,0,0]
#Adj_matrix_uav2: [1,0,1,1,1]
#Adj_matrix_uav3: [1,1,0,1,0]
#Adj_matrix_uav4: [0,1,1,0,1]
#Adj_matrix_uav5: [0,1,0,1,0]

Adj_matrix_uav39: [0]

#Adj_matrix_uav1: [0,0,0,0,0]
#Adj_matrix_uav2: [0,0,0,0,0]
#Adj_matrix_uav3: [0,0,0,0,0]
#Adj_matrix_uav4: [0,0,0,0,0]
#Adj_matrix_uav5: [0,0,0,0,0]

# control approach params
controlled_dimensions: 3

max_distance_to_initial_position: 2.0


d1: 1.0 
d2: 1.0
d3: 1.0
d4: 1.0
radius: 6.0 
betaD: 0.5  
beta_min: 0.1
dt: 0.02
step_size: 0.075


monitored_area_origin:
  x: 0.0
  y: 0.0
  z: 0.0

final_positions: # defined with respect to monitored_area_origin

  uav39:
    x: -6.0
    y: 45.0
    z: 1.1

  


initial_positions: # defined with respect to monitored_area_origin

  uav39:
    x: -68.0 #10
    y: -6.0 #0
    z: 1.1

