uav_names: ["uav1","uav2","uav3","uav4","uav5"] #, \"uav11\"]\n
# odometry_topic: "estimation_manager/ground_truth/odom"
odometry_topic: "estimation_manager/odom_main"

set_reference_timer:
  rate: 10 # [Hz]
  
size_neighbors1: 0.3
size_obstacles1: 0.1
encumbrance: 0.3
maximum_distance_conn: 10.0
noisy_measurements: 0.0 #0.15
noisy_angle: 0.0 #0.3
threshold: 1.5
window_length: 10 #10
bias_error: 0.0 #0.5


#Adj_matrix_uav1: [0,1,0,0,0]
#Adj_matrix_uav2: [1,0,1,0,0]
#Adj_matrix_uav3: [0,1,0,1,0]
#Adj_matrix_uav4: [0,0,1,0,1]
#Adj_matrix_uav5: [0,0,0,1,0]

Adj_matrix_uav1: [0,1,1,0,0]
Adj_matrix_uav2: [1,0,1,1,1]
Adj_matrix_uav3: [1,1,0,1,0]
Adj_matrix_uav4: [0,1,1,0,1]
Adj_matrix_uav5: [0,1,0,1,0]

#Adj_matrix_uav1: [0,0,0,0,0]
#Adj_matrix_uav2: [0,0,0,0,0]
#Adj_matrix_uav3: [0,0,0,0,0]
#Adj_matrix_uav4: [0,0,0,0,0]
#Adj_matrix_uav5: [0,0,0,0,0]

# control approach params
controlled_dimensions: 3

max_distance_to_initial_position: 2.0


d1: 0.1
d2: 0.75
d3: 0.1
d4: 0.75
radius: 6.0 
betaD: 3.0  
beta_min: 0.1
dt: 0.033
step_size: 0.075


monitored_area_origin:
  x: 0.0
  y: 0.0
  z: 0.0

final_positions: # defined with respect to monitored_area_origin

  uav1:
    x: -6.0
    y: 45.0
    z: 3.0

  uav2:
    x: 0
    y: 45.0
    z: 3.0

  uav3:
    x: -3.0
    y: 48.0
    z: 3.0
  
  uav4:
    x: 3.0
    y: 48.0
    z: 3.0

  uav5:
    x: 6
    y: 45.0
    z: 3.0


initial_positions: # defined with respect to monitored_area_origin

  uav1:
    x: -6.0 #10
    y: -42.0 #0
    z: 2.0

  uav2:
    x: -0.0 #6.2348980185873355
    y: -42.0 #7.818314824680298
    z: 2.0

  uav3:
    x: -3.0 #-2.22520933956314
    y: -39.0 #9.7492791218
    z: 2.0
  
  uav4:
    x: 3.0 #-9.00968867
    y: -39.0 #4.33883739
    z: 2.0

  uav5:
    x: 6.0 #-9.00968
    y: -42.0 #-4.3388373
    z: 2.0

