uav_names: ["uav1", "uav2", "uav3", "uav4", "uav5"] #, "uav11"]

# odometry_topic: "estimation_manager/ground_truth/odom"
odometry_topic: "estimation_manager/odom_main"

set_reference_timer:
  rate: 10 # [Hz]
  
size_neighbors1: 2.5
size_obstacles1: 0.5
maximum_distance_conn: 15.0
noisy_measurements: 0.15
threshold: 1.5

Adj_matrix_uav1: [0,1,1,0,0]
Adj_matrix_uav2: [1,0,1,1,1]
Adj_matrix_uav3: [1,1,0,1,0]
Adj_matrix_uav4: [0,1,1,0,1]
Adj_matrix_uav5: [0,1,0,1,0]


# control approach params
controlled_dimensions: 3

max_distance_to_initial_position: 2.0


d1: 0.5
d2: 4.0
d3: 0.5
d4: 4.0
radius: 10.0 
encumbrance: 2.5
betaD: 1.5
beta_min: 0.1
dt: 0.01
step_size: 0.075

obstacle1 : [-3.0,24.0]
obstacle2 : [6.5,19.0]
obstacle3 : [-4.5,15.0]
obstacle4 : [-12.0,20.0]
obstacle5 : [7.0,30.0]
obstacle6 : [17.0,25.0]
obstacle7 : [-10.0,35.0]

monitored_area_origin:
  x: 0.0
  y: 0.0
  z: 0.0



final_positions: # defined with respect to monitored_area_origin

  uav1:
    x: 0.0
    y: 45.0
    z: 3.0

  uav2:
    x: 0
    y: 45.0
    z: 3.0

  uav3:
    x: 0
    y: 45.0
    z: 3.0
  
  uav4:
    x: 0
    y: 45.0
    z: 3.0

  uav5:
    x: 0
    y: 45.0
    z: 3.0


initial_positions: # defined with respect to monitored_area_origin

  uav1:
    x: -8.0 #10
    y: -10.0 #0
    z: 2.0

  uav2:
    x: -0.0 #6.2348980185873355
    y: -10.0 #7.818314824680298
    z: 2.0

  uav3:
    x: -4.0 #-2.22520933956314
    y: -4.0 #9.7492791218
    z: 2.0
  
  uav4:
    x: 4.0 #-9.00968867
    y: -4.0 #4.33883739
    z: 2.0

  uav5:
    x: 8.0 #-9.00968
    y: -10.0 #-4.3388373
    z: 2.0

