uav_names: ["uav1", "uav2", "uav3", "uav4", "uav5"] #, "uav11"]

# odometry_topic: "estimation_manager/ground_truth/odom"
odometry_topic: "estimation_manager/odom_main"

set_reference_timer:
  rate: 10 # [Hz]
  
size_neighbors1: 2.5
size_obstacles1: 1.0
maximum_distance_conn: 15.0
encumbrance: 2.5



Adj_matrix_uav1: [0,0,0,0,0]
Adj_matrix_uav2: [0,0,0,0,0]
Adj_matrix_uav3: [0,0,0,0,0]
Adj_matrix_uav4: [0,0,0,0,0]
Adj_matrix_uav5: [0,0,0,0,0]


# control approach params
controlled_dimensions: 3

max_distance_to_initial_position: 2.0


d1: 0.25
d2: 0.3
d3: 0.25
d4: 0.3
radius: 3.0 
encumbrance: 2.5
betaD: 2.0
beta_min: 1.5
dt: 0.01
step_size: 0.075

obstacle1: [-3.0,24.0]
obstacle2 : [6.5,19.0]
obstacle3 : [-4.5,15.0]

monitored_area_origin:
  x: 0.0
  y: 0.0
  z: 0.0



final_positions: # defined with respect to monitored_area_origin

  uav1:
    x: 0.0
    y: 40.0
    z: 3.0

  uav2:
    x: 6.0
    y: 40.0
    z: 3.0

  uav3:
    x: -6.0
    y: 40.0
    z: 3.0
  
  uav4:
    x: 4.0
    y: 35.0
    z: 3.0

  uav5:
    x: -4.0
    y: 35.0
    z: 3.0


initial_positions: # defined with respect to monitored_area_origin

  uav1:
    x: -8.0 #10
    y: 0.0 #0
    z: 2.0

  uav2:
    x: -0.0 #6.2348980185873355
    y: 0.0 #7.818314824680298
    z: 2.0

  uav3:
    x: -4.0 #-2.22520933956314
    y: 6.0 #9.7492791218
    z: 2.0
  
  uav4:
    x: 4.0 #-9.00968867
    y: 6.0 #4.33883739
    z: 2.0

  uav5:
    x: 8.0 #-9.00968
    y: 0.0 #-4.3388373
    z: 2.0

