simulation_rate: 100.0
clock_rate: 100.0
realtime_factor: 0.2

iterate_without_input: true

individual_takeoff_platform:
  enabled: false

collisions:
  enabled: true
  crash: true

  # if crash==false, then the collisions are elastic
  rebounce: 100.0

# randomization of the initial conditions around the desired spawn point
randomization:

  enabled: false

  bounds:
    x: 15.0
    y: 15.0
    z: 15.0

ground:
  enabled: true
  z: 0.0 # [m]
#


uav_names: [
  "uav1",
  "uav2",
  "uav3",
  "uav4",
  "uav5",
  "uav6",
  "uav7",
  "uav8",
  "uav9",
  "uav10",
  "uav11",
  "uav12",
  "uav13",
  "uav14",
  "uav15",
]



uav1:
  type: "x500"
  spawn:
    x: 9.78
    y: -2.08
    z: 5.0
    heading: 0.0

uav2:
  type: "x500"
  spawn:
    x: 9.78
    y: 2.08
    z: 5.0
    heading: 0.0

uav3:
  type: "x500"
  spawn:
    x: 8.09
    y: 5.88
    z: 5.0
    heading: 0.0

uav4:
  type: "x500"
  spawn:
    x: 5.00
    y: 8.66
    z: 5.0
    heading: 0.0

uav5:
  type: "x500"
  spawn:
    x: 1.05
    y: 9.95
    z: 5.0
    heading: 0.0

uav6:
  type: "x500"
  spawn:
    x: -3.09
    y: 9.51
    z: 5.0
    heading: 0.0

uav7:
  type: "x500"
  spawn:
    x: -6.69
    y: 7.43
    z: 5.0
    heading: 0.0

uav8:
  type: "x500"
  spawn:
    x: -9.14
    y: 4.07
    z: 5.0
    heading: 0.0

uav9:
  type: "x500"
  spawn:
    x: -10.00
    y: -0.00
    z: 5.0
    heading: 0.0

uav10:
  type: "x500"
  spawn:
    x: -9.14
    y: -4.07
    z: 5.0
    heading: 0.0

uav11:
  type: "x500"
  spawn:
    x: -6.69
    y: -7.43
    z: 5.0
    heading: 0.0

uav12:
  type: "x500"
  spawn:
    x: -3.09
    y: -9.51
    z: 5.0
    heading: 0.0

uav13:
  type: "x500"
  spawn:
    x: 1.05
    y: -9.95
    z: 5.0
    heading: 0.0

uav14:
  type: "x500"
  spawn:
    x: 5.00
    y: -8.66
    z: 5.0
    heading: 0.0

uav15:
  type: "x500"
  spawn:
    x: 8.09
    y: -5.88
    z: 5.0
    heading: 0.0

