uav_names: ["uav1", "uav3", "uav7", "uav8", "uav31", "uav32", "uav37"] #, "uav11"]

# odometry_topic: "estimation_manager/ground_truth/odom"
odometry_topic: "estimation_manager/odom_main"

set_reference_timer:
  rate: 10 # [Hz]
  
size_neighbors1: 2.5
size_obstacles1: 2.5
maximum_distance_conn: 1.0
encumbrance: 2.5

size_neighbors1: 2.5
size_obstacles1: 2.5
maximum_distance_conn: 15.0

Adj_matrix_uav1: [0,0,0,0,0]
Adj_matrix_uav3: [0,0,0,0,0]
Adj_matrix_uav7: [0,0,0,0,0]
Adj_matrix_uav8: [0,0,0,0,0]
Adj_matrix_uav31: [0,0,0,0,0]
Adj_matrix_uav32: [0,0,0,0,0]
Adj_matrix_uav37: [0,0,0,0,0]


# control approach params
controlled_dimensions: 3

max_distance_to_initial_position: 2.0

d1: 0.2
d2: 1.0
d3: 0.2
d4: 1.0
radius: 3.0 
encumbrance: 2.5
betaD: 1.5
beta_min: 1.0
dt: 0.01
step_size: 0.075

obstacle1: [-50.0,1.0] #-3.0,24.0]
obstacle2 : [-50.0,1.0] #6.5,19.0]
obstacle3 : [-50.0,1.0] #-4.5,15.0]


final_positions: # defined with respect to monitored_area_origin

  uav1:
    x: -15.0
    y: 0
    z: 3.0

  uav3:
    x: -9.35
    y: -11.72
    z: 3.0

  uav7:
    x: 3.33
    y: -14.62
    z: 3.0
  
  uav8:
    x: 13.51
    y: -6.50
    z: 3.0

  uav31:
    x: 13.51
    y: 6.50
    z: 3.0

  uav32:
    x: 3.33
    y: 14.62
    z: 3.0

  uav37:
    x: -9.35
    y: 11.72
    z: 3.0

monitored_area_origin:
  x: -30.0
  y: 10.0
  z: 5.0

initial_positions: # defined with respect to monitored_area_origin

  uav1:
    x: 15.0
    y: 0
    z: 3.0

  uav3:
    x: 9.35
    y: 11.72
    z: 3.0

  uav7:
    x: -3.33
    y: 14.62
    z: 3.0
  
  uav8:
    x: -13.51
    y: 6.50
    z: 3.0

  uav31:
    x: -13.51
    y: -6.50
    z: 3.0

  uav32:
    x: -3.33
    y: -14.62
    z: 3.0

  uav37:
    x: 9.35
    y: -11.72
    z: 3.0

