# uav_names: ["uav37","uav40","uav39"] #,"uav40","uav41"] #, \"uav11\"]\n
uav_names: ["uav37","uav41"] #,"uav40","uav41"] #, \"uav11\"]\n
uav_uvdar_ids: [1,3]
# odometry_topic: "estimation_manager/ground_truth/odom"
odometry_topic: "estimation_manager/odom_main"

set_reference_timer:
  rate: 10 # [Hz]
  
size_neighbors1: 0.3 
size_obstacles1: 0.05
encumbrance: 0.3
maximum_distance_conn: 12.0
noisy_measurements: 0.0 #0.15
noisy_angle: 0.0 #0.3
threshold: 1.5 
window_length: 1 #10
bias_error: 0.0 #0.5

#Adj_matrix_uav1: [0,1,1,0,0]
#Adj_matrix_uav2: [1,0,1,1,1]
#Adj_matrix_uav3: [1,1,0,1,0]
#Adj_matrix_uav4: [0,1,1,0,1]
#Adj_matrix_uav5: [0,1,0,1,0]

Adj_matrix_uav37: [0,1]
Adj_matrix_uav41: [1,0]

#Adj_matrix_uav1: [0,0,0,0,0]
#Adj_matrix_uav2: [0,0,0,0,0]
#Adj_matrix_uav3: [0,0,0,0,0]
#Adj_matrix_uav4: [0,0,0,0,0]
#Adj_matrix_uav5: [0,0,0,0,0]

# control approach params
controlled_dimensions: 3

max_distance_to_initial_position: 2.0


d1: 0.5 
d2: 1.0
d3: 0.5
d4: 1.0
radius: 4.5 
betaD: 3.0  
beta_min: 0.1
dt: 0.03
step_size: 0.10


monitored_area_origin:
  x: 0.0
  y: 0.0
  z: 0.0

final_positions: # TODO 

  uav37:
    x: -6.0
    y: 45.0
    z: 3.0

  uav41:
    x: 0
    y: 45.0
    z: 3.0
 


initial_positions: # defined with respect to monitored_area_origin

  uav37:
    x: -80.0 #10
    y: 7.0 
    z: 2.0

  uav41:
    x: -74.0 #6.2348980185873355
    y: 10.62 #7.818314824680298
    z: 2.0
