mrs_uav_managers:

  estimation_manager:

    # loaded state estimator plugins
    # available in mrs_uav_state_estimators: gps_garmin, gps_baro, rtk, aloam, ground_truth, dummy
    state_estimators: [
    "gps_baro",
    "gps_garmin",
    # "rtk",
    # "aloam",
    # "ground_truth",
    # "dummy"
    ]

    initial_state_estimator: "gps_garmin" # will be used as the first state estimator
    agl_height_estimator: "garmin_agl" # only slightly filtered height for checking min height (not used in control feedback)
    gps_garmin:
      lat_gps:

        max_flight_z: 100.0

        innovation:
          limit: 0.5
          action: "mitigate"

mrs_uav_trackers:

  mpc_tracker:
    # mrs collision avoidance
    collision_avoidance:

      enabled:           true # disabling this will stop this UAV to react to others, but it will still transmit data to others
      enabled_passively: false # disabling this will stop this uav to even transmit its data to others (only if enabled: false)
      radius: 2.0 # [m]
      correction: 3.0 # [m]
