# uav_names: ["uav37","uav40","uav39"] #,"uav40","uav41"] #, \"uav11\"]\n
uav_names: ["uav33","uav40","uav41"] #,"uav40","uav41"] #, \"uav11\"]\n
uav_uvdar_ids: [0,3,4] 
# odometry_topic: "estimation_manager/ground_truth/odom"
odometry_topic: "estimation_manager/odom_main"

set_reference_timer:
  rate: 10 # [Hz]
  
size_neighbors1: 0.3 
size_obstacles1: 0.1
encumbrance: 0.3
maximum_distance_conn: 12.0
noisy_measurements: 0.0 #0.15
noisy_angle: 0.0 #0.3
threshold: 0.8 
window_length: 1 #10
bias_error: 0.0 #0.5



cwvd: 0.95
refZ: 1.1
max_obstacle_integration_dist: 8.0
#Adj_matrix_uav1: [0,1,1,0,0]
#Adj_matrix_uav2: [1,0,1,1,1]
#Adj_matrix_uav3: [1,1,0,1,0]
#Adj_matrix_uav4: [0,1,1,0,1]
#Adj_matrix_uav5: [0,1,0,1,0]

Adj_matrix_uav33: [0,1,0]
Adj_matrix_uav40: [1,0,1]
Adj_matrix_uav41: [0,1,0]

#Adj_matrix_uav1: [0,0,0,0,0]
#Adj_matrix_uav2: [0,0,0,0,0]
#Adj_matrix_uav3: [0,0,0,0,0]
#Adj_matrix_uav4: [0,0,0,0,0]
#Adj_matrix_uav5: [0,0,0,0,0]

# control approach params
controlled_dimensions: 3

max_distance_to_initial_position: 2.0


d1: 0.2 
d2: 1.0
d3: 0.2
d4: 1.0
radius: 4.5 
betaD: 3.0  
beta_min: 1.5
dt: 0.01
step_size: 0.075


monitored_area_origin:
  x: 0.0
  y: 0.0
  z: 0.0

final_positions: # TODO 

  uav33:
    x: 40.0 
    y: 0.0
    z: 1.1 

  uav40:
    x: 40.0
    y: 0.0
    z: 1.1

  uav41:
    x: 40.0
    y: 0.0
    z: 1.1
  


initial_positions: # defined with respect to monitored_area_origin

  uav33:
    x: -80.0 #10
    y: 7.0 
    z: 2.0

  uav40:
    x: -74.0 #6.2348980185873355
    y: 10.62 #7.818314824680298
    z: 2.0

  uav41:
    x: -80.0 #-2.22520933956314
    y: 10.0
    z: 2.0
