safe_obstacle_distance:
  default: 0.7 # [m]

euclidean_distance_cutoff: 0.7 # [m]

unknown_is_occupied: false # if false, planning through unknown space is enabled

# trajectory_generator:
  # input_trajectory_length: 5.0 # [s] (the rest of path will be ignored during trajectory generation)

subt_planner:
  use: false