uav_names: ["uav1", "uav2", "uav3", "uav4", "uav5"] #, "uav11"]

# odometry_topic: "estimation_manager/ground_truth/odom"
odometry_topic: "estimation_manager/odom_main"

set_reference_timer:
  rate: 10 # [Hz]
  
size_neighbors1: 0.2
size_obstacles1: 0.5
encumbrance: 0.2
maximum_distance_conn: 7.5
noisy_measurements: 0.0 #0.15
noisy_angle: 0.0 #0.3
threshold: 2.0
window_length: 1 #10
bias_error: 0.0 #0.5



Adj_matrix_uav1: [0,0,0,0,0]
Adj_matrix_uav2: [0,0,0,0,0]
Adj_matrix_uav3: [0,0,0,0,0]
Adj_matrix_uav4: [0,0,0,0,0]
Adj_matrix_uav5: [0,0,0,0,0]


# control approach params
controlled_dimensions: 3

max_distance_to_initial_position: 2.0


d1: 0.1
d2: 2.0
d3: 0.1
d4: 2.0
radius: 6.0 
betaD: 3.0
beta_min: 0.1
dt: 0.033
step_size: 0.085

obstacle1 : [-30.0,24.0]
obstacle2 : [60.5,19.0]
obstacle3 : [-40.5,15.0]
obstacle4 : [-120.0,20.0]
obstacle5 : [70.0,30.0]
obstacle6 : [170.0,25.0]
obstacle7 : [-100.0,35.0]
obstacle8 : [100.0,0.0]
obstacle9 : [-40.0,-15.0]
obstacle10 : [-120.0,-20.0]
obstacle11 : [70.0,-30.0]
obstacle12 : [170.0,-25.0]
obstacle13 : [-100.0,-35.0]

monitored_area_origin:
  x: 0.0
  y: 0.0
  z: 0.0

final_positions: # defined with respect to monitored_area_origin

  uav1:
    x: 10.0
    y: 0.0 
    z: 3.0

  uav2:
    x: 3.09
    y: 9.51
    z: 3.0

  uav3:
    x: -8.09
    y: 5.87
    z: 3.0
  
  uav4:
    x: -8.09
    y: -5.87
    z: 3.0

  uav5:
    x: 3.09
    y: -9.51
    z: 3.0


initial_positions: # defined with respect to monitored_area_origin

  uav1:
    x: -10.0 #10
    y: 0.0 #0
    z: 2.0

  uav2:
    x: -3.09 #6.2348980185873355
    y: -9.51 #7.818314824680298
    z: 2.0

  uav3:
    x: 8.09 #-2.22520933956314
    y: -5.87 #9.7492791218
    z: 2.0
  
  uav4:
    x: 8.09 #-9.00968867
    y: 5.87 #4.33883739
    z: 2.0

  uav5:
    x: -3.09 #-9.00968
    y: 9.51 #-4.3388373
    z: 2.0

