simulation_rate: 200.0
clock_rate: 100.0
realtime_factor: 0.4

iterate_without_input: true

individual_takeoff_platform:
  enabled: false

collisions:
  enabled: true
  crash: true

  # if crash==false, then the collisions are elastic
  rebounce: 100.0

# randomization of the initial conditions around the desired spawn point
randomization:

  enabled: false

  bounds:
    x: 15.0
    y: 15.0
    z: 15.0

ground:
  enabled: true
  z: 0.0 # [m]
#


uav_names: [
  "uav1",
  "uav2",
  "uav3",
  "uav4",
  "uav5",  
  "uav6",
  "uav7",

]

uav1:
  type: "x500"
  spawn:
    x: 10
    y: 0
    z: 2.0
    heading: 0.0

uav2:
  type: "x500"
  spawn:
    x: 6.2348980185873355
    y: 7.818314824680298
    z: 2.0
    heading: 0.0

uav3:
  type: "x500"
  spawn:
    x: -2.22520933956314
    y: 9.7492791218
    z: 2.0
    heading: 0.0

uav4:
  type: "x500"
  spawn:
    x: -9.00968867
    y: 4.33883739
    z: 2.0
    heading: 0.0

uav5:
  type: "x500"
  spawn:
    x: -9.00968
    y: -4.3388373
    z: 2.0
    heading: 0.0

uav6:
  type: "x500"
  spawn:
    x: -2.225209339
    y: -9.7492791218
    z: 2.0
    heading: 0.0

uav7:
  type: "x500"
  spawn:
    x: 6.2348980185
    y: -7.8183148
    z: 2.0
    heading: 0.0
    
uav8:
  type: "x500"
  spawn:
    x: -2.225209339
    y: -9.7492791218
    z: 2.0
    heading: 0.0

uav9:
  type: "x500"
  spawn:
    x: 6.2348980185
    y: -7.8183148
    z: 2.0
    heading: 0.0

uav10:
  type: "x500"
  spawn:
    x: 6.2348980185
    y: -7.8183148
    z: 2.0
    heading: 0.0




