uav_names: ["uav1", "uav2", "uav3", "uav4", "uav5", "uav6", "uav7"] #, "uav11"]

# odometry_topic: "estimation_manager/ground_truth/odom"
odometry_topic: "estimation_manager/odom_main"

set_reference_timer:
  rate: 10 # [Hz]
  
size_neighbors1: 2.5
size_obstacles1: 2.5
maximum_distance_conn: 12.0
encumbrance: 2.5

size_neighbors1: 2.5
size_obstacles1: 2.5
maximum_distance_conn: 15.0

Adj_matrix_uav1: [0,0,0,0,0]
Adj_matrix_uav2: [0,0,0,0,0]
Adj_matrix_uav3: [0,0,0,0,0]
Adj_matrix_uav4: [0,0,0,0,0]
Adj_matrix_uav5: [0,0,0,0,0]
Adj_matrix_uav6: [0,0,0,0,0]
Adj_matrix_uav7: [0,0,0,0,0]


# control approach params
controlled_dimensions: 3


d1: 0.2
d2: 1.0
d3: 0.2
d4: 1.0
radius: 3.0 
encumbrance: 2.5
betaD: 1.5
beta_min: 1.0
dt: 0.01
step_size: 0.075

obstacle1: [-20.0,1.0] #-3.0,24.0]
obstacle2 : [-20.0,1.0] #6.5,19.0]
obstacle3 : [-20.0,1.0] #-4.5,15.0]


final_positions: # defined with respect to monitored_area_origin

  uav1:
    x: -15.0
    y: 0
    z: 3.0

  uav2:
    x: -9.35
    y: -11.72
    z: 3.0

  uav3:
    x: 3.33
    y: -14.62
    z: 3.0
  
  uav4:
    x: 13.51
    y: -6.50
    z: 3.0

  uav5:
    x: 13.51
    y: 6.50
    z: 3.0

  uav6:
    x: 3.33
    y: 14.62
    z: 3.0

  uav7:
    x: -9.35
    y: 11.72
    z: 3.0
