simulation_rate: 200.0
clock_rate: 100.0
realtime_factor: 0.5

iterate_without_input: true

individual_takeoff_platform:
  enabled: false

collisions:
  enabled: true
  crash: true

  # if crash==false, then the collisions are elastic
  rebounce: 100.0

# randomization of the initial conditions around the desired spawn point
randomization:

  enabled: false

  bounds:
    x: 15.0
    y: 15.0
    z: 15.0

ground:
  enabled: true
  z: 0.0 # [m]
#


uav_names: [
  "uav1",
  "uav2",
  "uav3",
  "uav4",
  "uav5",  


]

uav1:
  type: "x500"
  spawn:
    x: -8.0 #10
    y: 0.0 #0
    z: 2.0
    heading: 0.0

uav2:
  type: "x500"
  spawn:
    x: -0.0 #6.2348980185873355
    y: 0.0 #7.818314824680298
    z: 2.0
    heading: 0.0

uav3:
  type: "x500"
  spawn:
    x: -4.0 #-2.22520933956314
    y: 6.0 #9.7492791218
    z: 2.0
    heading: 0.0

uav4:
  type: "x500"
  spawn:
    x: 4.0 #-9.00968867
    y: 6.0 #4.33883739
    z: 2.0
    heading: 0.0

uav5:
  type: "x500"
  spawn:
    x: 8.0 #-9.00968
    y: 0.0 #-4.3388373
    z: 2.0
    heading: 0.0


