uav_names: ["uav1", "uav2", "uav3", "uav4" ,"uav5", "uav6", "uav7","uav8", "uav9", "uav10"] #, "uav11"]

# odometry_topic: "estimation_manager/ground_truth/odom"
odometry_topic: "estimation_manager/odom_main"
uav_uvdar_ids: [1,2,3,4,5,6,7,8,9,10] # 0,1,2,3,4] #,"uav40","uav41"] #, \"uav11\"]\n

set_reference_timer:
  rate: 10 # [Hz]
  
size_neighbors1: 0.3 
size_obstacles1: 0.05 
encumbrance: 0.7 
maximum_distance_conn: 10.0
noisy_measurements: 0.0 #0.15
noisy_angle: 0.0 #0.3
threshold: 0.8 
window_length: 1 #10
bias_error: 0.0 #0.5
cwvd_obs: 0.75
cwvd_rob: 0.75
sim: true
refZ: 5.0
max_obstacle_integration_dist: 9.0

Adj_matrix_uav1: [0,0,0,0,0,0,0,0,0]
Adj_matrix_uav2: [0,0,0,0,0,0,0,0,0]
Adj_matrix_uav3: [0,0,0,0,0,0,0,0,0]
Adj_matrix_uav4: [0,0,0,0,0,0,0,0,0]
Adj_matrix_uav5: [0,0,0,0,0,0,0,0,0]
Adj_matrix_uav6: [0,0,0,0,0,0,0,0,0]
Adj_matrix_uav7: [0,0,0,0,0,0,0,0,0]
Adj_matrix_uav8: [0,0,0,0,0,0,0,0,0]
Adj_matrix_uav9: [0,0,0,0,0,0,0,0,0]
Adj_matrix_uav10: [0,0,0,0,0,0,0,0,0]

# control approach params
controlled_dimensions: 3

max_distance_to_initial_position: 2.0

#for 3D
min_z: 0.0  
max_z: 20.0

flag_3D: true
use_z_rule: false

use_livox_tilted: false
rotate_recieved_pcl: false #difference between simulation and livox
livox_tilt_deg: 45.0
livox_fov: 60.0

searchRadius: 0.6 #For meshing - max search for vertice in triangle SHOULD BE SET ACCORDINGLY WITH THE PCL I AM GETTING - mapping res 0.4 vox grid -> 0.6 serach radius
use_bonxai_mapping: true #if true usis mapping to shape the cell S otherwise it uses the pointcloud for slam IF FALSE set frame for rbl as uav29/livox
# if true set frame as point_lio_origin
use_voxel: true #I started to use meshing to cut cell A instead of this, but this seems as a smarter alternative - should work for mapping wiht bonxai and also with raw point cloud
map_resolution: 0.3

d1: 0.5
d2: 1.0
d3: 0.5
d4: 1.0
d5: 0.5
d6: 1.0
d7: 0.2
radius: 3.5  #point lio 
betaD: 1.5 
beta_min: 0.1
dt: 0.15
step_size: 0.66


monitored_area_origin:
  x: 0.0
  y: 0.0
  z: 0.0

final_positions: # defined with respect to monitored_area_origin
  uav1:
    x: 0.00
    y: 0.00
    z: 1.00

  uav2:
    x: 2.32
    y: 2.12
    z: 2.11

  uav3:
    x: -0.36
    y: -4.14
    z: 3.22

  uav4:
    x: -2.87
    y: 3.74
    z: 4.33

  uav5:
    x: 4.89
    y: -0.87
    z: 5.44

  uav6:
    x: -4.19
    y: -2.67
    z: 6.56

  uav7:
    x: 1.22
    y: 4.55
    z: 7.67

  uav8:
    x: 1.92
    y: -3.69
    z: 8.78

  uav9:
    x: -2.95
    y: 1.08
    z: 9.89

  uav10:
    x: 0.00
    y: 0.00
    z: 11.00

initial_positions: # defined with respect to monitored_area_origin
  uav1:
    x: 0.00
    y: 0.00
    z: 11.00

  uav2:
    x: -2.32
    y: -2.12
    z: 9.89

  uav3:
    x: 0.36
    y: 4.14
    z: 8.78

  uav4:
    x: 2.87
    y: -3.74
    z: 7.67

  uav5:
    x: -4.89
    y: 0.87
    z: 6.56

  uav6:
    x: 4.19
    y: 2.67
    z: 5.44

  uav7:
    x: -1.22
    y: -4.55
    z: 4.33

  uav8:
    x: -1.92
    y: 3.69
    z: 3.22

  uav9:
    x: 2.95
    y: -1.08
    z: 2.11

  uav10:
    x: -0.00
    y: -0.00
    z: 1.00