#uav_names: ["uav1", "uav2", "uav3", "uav7", "uav8", "uav13"]
uav_names: ["uav1", "uav7", "uav8"]

# odometry_topic: "estimation_manager/ground_truth/odom"
odometry_topic: "estimation_manager/odom_main"

set_reference_timer:
  rate: 10 # [Hz]
  
  
  
  
d1: 0.2
d2: 1
d3: 0.2
d4: 1
radius: 3
encumbrance: 2.3
betaD: 1.5
beta_min: 0.8
dt: 0.05
step_size: 0.05
maximum_distance_conn: 17.0


#size_neighbors: [2.3,2.3,2.3,2.3]

#size_neighbors_and_obstacles: [2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3]
size_obstacles: [2.3,2.3,2.3]
#obstacle1: [-3.0,24.0]
#obstacle2 : [6.5,19.0]
#obstacle3 : [-4.5,15.0]

size_neighbors: [2.3,2.3]

size_neighbors_and_obstacles: [2.3, 2.3, 2.3, 2.3, 2.3]

maximum_distance_conn: 17.0
