uav_names: ["uav4", "uav5", "uav6","uav7","uav8"] #, "uav11"]

# odometry_topic: "estimation_manager/ground_truth/odom"
odometry_topic: "estimation_manager/odom_main"

set_reference_timer:
  rate: 10 # [Hz]
  
size_neighbors1: 2.5
size_obstacles1: 2.5
maximum_distance_conn: 15.0

Adj_matrix_uav4: [0,1,0,1,0]
Adj_matrix_uav5: [1,1,1,1,1]
Adj_matrix_uav6: [0,1,0,0,1]
Adj_matrix_uav7: [1,1,0,0,1]
Adj_matrix_uav8: [0,1,1,1,0]



final_positions: # defined with respect to monitored_area_origin

  uav4:
    x: -15.0
    y: 42.0
    z: 3.0

  uav5:
    x: -15.0
    y: 36.0
    z: 3.0

  uav6:
    x: -15.0
    y: 30.0
    z: 3.0

  uav7:
    x: -15.0
    y: 30.0
    z: 3.0

  uav8:
    x: -15.0
    y: 30.0
    z: 3.0


