simulation_rate: 100.0
clock_rate: 100.0
realtime_factor: 0.7

iterate_without_input: true

individual_takeoff_platform:
  enabled: false

collisions:
  enabled: true
  crash: true

  # if crash==false, then the collisions are elastic
  rebounce: 100.0

# randomization of the initial conditions around the desired spawn point
randomization:

  enabled: false

  bounds:
    x: 15.0
    y: 15.0
    z: 15.0

ground:
  enabled: true
  z: 0.0 # [m]
#


uav_names: [
  "uav1",
  "uav2",
  "uav3",
  "uav4",
  "uav5",
  "uav6",
  "uav7",
  "uav8",
  "uav9",
  "uav10",
  "uav11",
  "uav12",
  "uav13",
  "uav14",
  "uav15",
]


uav1:
  type: "x500"
  spawn:
    x: 0.00
    y: 0.00
    z: 11.00
    heading: 0.0

uav2:
  type: "x500"
  spawn:
    x: -1.90
    y: -1.74
    z: 10.29
    heading: 0.0

uav3:
  type: "x500"
  spawn:
    x: 0.31
    y: 3.49
    z: 9.57
    heading: 0.0

uav4:
  type: "x500"
  spawn:
    x: 2.50
    y: -3.26
    z: 8.86
    heading: 0.0

uav5:
  type: "x500"
  spawn:
    x: -4.45
    y: 0.79
    z: 8.14
    heading: 0.0

uav6:
  type: "x500"
  spawn:
    x: 4.04
    y: 2.57
    z: 7.43
    heading: 0.0

uav7:
  type: "x500"
  spawn:
    x: -1.28
    y: -4.78
    z: 6.71
    heading: 0.0

uav8:
  type: "x500"
  spawn:
    x: -2.30
    y: 4.44
    z: 6.00
    heading: 0.0

uav9:
  type: "x500"
  spawn:
    x: 4.65
    y: -1.70
    z: 5.29
    heading: 0.0

uav10:
  type: "x500"
  spawn:
    x: -4.43
    y: -1.83
    z: 4.57
    heading: 0.0

uav11:
  type: "x500"
  spawn:
    x: 1.91
    y: 4.09
    z: 3.86
    heading: 0.0

uav12:
  type: "x500"
  spawn:
    x: 1.23
    y: -3.92
    z: 3.14
    heading: 0.0

uav13:
  type: "x500"
  spawn:
    x: -3.03
    y: 1.75
    z: 2.43
    heading: 0.0

uav14:
  type: "x500"
  spawn:
    x: 2.52
    y: 0.55
    z: 1.71
    heading: 0.0

uav15:
  type: "x500"
  spawn:
    x: -10.00
    y: -0.00
    z: 1.00
    heading: 0.0

