uav_names: ["uav1", "uav2", "uav3", "uav4" ,"uav5", "uav6", "uav7","uav8", "uav9", "uav10"] #, "uav11"]

# odometry_topic: "estimation_manager/ground_truth/odom"
odometry_topic: "estimation_manager/odom_main"
uav_uvdar_ids: [1,2,3,4,5,6,7,8,9,10] # 0,1,2,3,4] #,"uav40","uav41"] #, \"uav11\"]\n

set_reference_timer:
  rate: 10 # [Hz]
  
size_neighbors1: 0.3 
size_obstacles1: 0.05 
encumbrance: 0.3 
maximum_distance_conn: 10.0
noisy_measurements: 0.0 #0.15
noisy_angle: 0.0 #0.3
threshold: 0.8 
window_length: 1 #10
bias_error: 0.0 #0.5
cwvd_obs: 0.9
cwvd_rob: 0.9
sim: true
refZ: 10.0
max_obstacle_integration_dist: 9.0

Adj_matrix_uav1: [0,0,0,0,0,0,0,0,0]
Adj_matrix_uav2: [0,0,0,0,0,0,0,0,0]
Adj_matrix_uav3: [0,0,0,0,0,0,0,0,0]
Adj_matrix_uav4: [0,0,0,0,0,0,0,0,0]
Adj_matrix_uav5: [0,0,0,0,0,0,0,0,0]


# control approach params
controlled_dimensions: 3

max_distance_to_initial_position: 2.0

#for 3D
min_z: 0.0  
max_z: 20.0

flag_3D: true
use_z_rule: false

use_livox_tilted: false
rotate_recieved_pcl: false #difference between simulation and livox
livox_tilt_deg: 45.0

d1: 0.5
d2: 1.0
d3: 0.5
d4: 1.0
d5: 0.5
d6: 1.0
d7: 0.2
radius: 3.5  #point lio 
betaD: 1.5 
beta_min: 0.1
dt: 0.15
step_size: 0.66


monitored_area_origin:
  x: 0.0
  y: 0.0
  z: 0.0

final_positions: # defined with respect to monitored_area_origin
  uav1:
    x: -8.09
    y: 5.88
    z: 10.0

  uav2:
    x: -8.09
    y: -5.88
    z: 10.0

  uav3:
    x: 3.09
    y: -9.51
    z: 10.0

  uav4:
    x: 10.00
    y: 0.00
    z: 10.0

  uav5:
    x: 3.09
    y: 9.51
    z: 10.0

initial_positions: # defined with respect to monitored_area_origin
  uav1:
    x: 8.09
    y: -5.88
    z: 10.0

  uav2:
    x: 8.09
    y: 5.88
    z: 10.0

  uav3:
    x: -3.09
    y: 9.51
    z: 10.0

  uav4:
    x: -10.00
    y: -0.00
    z: 10.0

  uav5:
    x: -3.09
    y: -9.51
    z: 10.0